export const FORM_ORDER = 'orderForm'
export const UPDATE_FORM_STATE = 'UPDATE_FORM_STATE'

export const FIELD_SIZE = 'FIELD_SIZE'

export const FIELD_COLOR_SHADE = 'FIELD_COLOR_SHADE'
export const FIELD_COLOR_CODE = 'FIELD_COLOR_CODE'
export const FIELD_WIDTH = 'FIELD_WIDTH'
export const FIELD_LENGTH = 'FIELD_LENGTH'
export const FIELD_THICKNESS = 'FIELD_THICKNESS'
export const FIELD_COUNT = 'FIELD_COUNT'
